#!/usr/bin/bash

xrandr --output eDP-1 --right-of HDMI-2

hc lock

script_dir=$HOME/.config/herbstluftwm
. $HOME/.cache/wal/colors.sh

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

hc keybind $Mod-c close_or_remove
hc keybind $Mod-Shift-c remove

hc keybind $Mod-Return spawn $script_dir/spawn_urxvt.sh
hc keybind $Mod-Shift-Return spawn urxvt
hc keybind $Mod-d spawn dmenu_run

hc keybind XF86MonBrightnessUp exec xbacklight -inc 5
hc keybind XF86MonBrightnessDown exec xbacklight -dec 5

# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

# moving clients
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

# splitting frames
hc keybind $Mod-u              split bottom  0.5
hc keybind $Mod-o              split right   0.5
hc keybind $Mod-i              split auto
hc keybind $Mod-Control-space  split explode
hc keybind $Mod-r              rotate

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h resize left  +$resizestep
hc keybind $Mod-Control-j resize down  +$resizestep
hc keybind $Mod-Control-k resize up    +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Shift-period move_index +1
hc keybind $Mod-Shift-comma  move_index -1

# layouting
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                         \
            or , and . compare tags.focus.curframe_wcount = 2                 \
                     . cycle_layout +1 vertical max grid  \
               , cycle_layout +1 vertical max

# mouse
hc mouseunbind --all

# focus
hc keybind $Mod-Tab cycle

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

hc set frame_border_active_color orange
hc set frame_border_normal_color '#5c4459'

hc set frame_bg_normal_color red #'#565656'
hc set frame_bg_active_color green #'#345F0C'

hc set frame_border_width 1
hc set always_show_frame 1

hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 10

hc keybind $Mod-F10 cycle_value frame_gap 0 10 20 40
hc keybind $Mod-F11 spawn $script_dir/toggle_compton.sh

hc keybind $Mod-F12 spawn compton-trans -c 85
hc keybind $Mod-Shift-F12 spawn compton-trans -c 100

cache_dir=$HOME/.cache/herbsluftwm
mkdir -p $cache_dir

hc attr theme.active.color orange
hc attr theme.normal.color '#5c4459' #'#454545'
hc attr theme.urgent.color orange

hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 3

hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black

hc attr theme.active.inner_color green #'#3E4A00'
hc attr theme.active.outer_color orange #'#3E4A00'
hc attr theme.background_color magenta #'#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set default_frame_layout 0
hc set focus_stealing_prevention 1

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
# give focus to most common terminals
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'
hc set swap_monitors_to_get_tag 1
hc set focus_stealing_prevention 1
hc set focus_crosses_monitor_boundaries 1
hc set auto_detect_monitors 1
hc detect_monitors

pkill -f bar; $script_dir/bar.sh &

# unlock, just to be sure
hc unlock
hc emit_hook reload

